Repository kik548/ISO2-2022-C05, pull requests merged in 2022-12, with the labels that each got.

#28 Iteración 1 Pruebas
  Pilgrimfy/it1-cliente/src/test/java/org/it1/cliente/presentacion/InterfazPeregrinoEtapaTest.java
  Pilgrimfy/it1-servidor/src/test/java/org/it1/servidor/dominio/CaminoTest.java
  Pilgrimfy/it1-servidor/src/test/java/org/it1/servidor/dominio/EtapaTest.java
  Pilgrimfy/it1-servidor/src/test/java/org/it1/servidor/dominio/GestorCaminosTest.java
  Pilgrimfy/it1-servidor/src/test/java/org/it1/servidor/dominio/GestorEtapaTest.java
  Pilgrimfy/it1-servidor/src/test/java/org/it1/servidor/persistencia/AgenteTest.java
Labels: Pruebas

#29 Iteración2
  .project
  Pilgrimfy/it1-cliente/pom.xml
  Pilgrimfy/it1-servidor/pom.xml
  Pilgrimfy/it1/.gitignore
  Pilgrimfy/it1/.project
  Pilgrimfy/it1/target/classes/META-INF/MANIFEST.MF
  Pilgrimfy/it1/target/classes/META-INF/maven/ISO2-C05/it1/pom.properties
  Pilgrimfy/it1/target/classes/META-INF/maven/ISO2-C05/it1/pom.xml
  Pilgrimfy/it2-cliente/.classpath
  Pilgrimfy/it2-cliente/.gitignore
  Pilgrimfy/it2-cliente/.project
  Pilgrimfy/it2-cliente/.settings/org.eclipse.core.resources.prefs
  Pilgrimfy/it2-cliente/.settings/org.eclipse.jdt.core.prefs
  Pilgrimfy/it2-cliente/.settings/org.eclipse.m2e.core.prefs
  Pilgrimfy/it2-cliente/pom.xml
  Pilgrimfy/it2-cliente/src/main/java/org/it2/cliente/presentacion/InterfazNegocio.java
  Pilgrimfy/it2-cliente/src/test/java/org/it2/cliente/AppTest.java
  Pilgrimfy/it2-servidor/.classpath
  Pilgrimfy/it2-servidor/.gitignore
  Pilgrimfy/it2-servidor/.project
  Pilgrimfy/it2-servidor/.settings/org.eclipse.core.resources.prefs
  Pilgrimfy/it2-servidor/.settings/org.eclipse.jdt.core.prefs
  Pilgrimfy/it2-servidor/.settings/org.eclipse.m2e.core.prefs
  Pilgrimfy/it2-servidor/pom.xml
  Pilgrimfy/it2-servidor/src/main/java/org/it2/servidor/dominio/GestorNegocio.java
  Pilgrimfy/it2-servidor/src/main/java/org/it2/servidor/dominio/Negocio.java
  Pilgrimfy/it2-servidor/src/main/java/org/it2/servidor/persistencia/Agente.java
  Pilgrimfy/it2-servidor/src/test/java/org/it2/servidor/AppTest.java
  Pilgrimfy/pom.xml
Labels: Implementación

#40 Iteración4
  Pilgrimfy/it4-cliente/.classpath
  Pilgrimfy/it4-cliente/.gitignore
  Pilgrimfy/it4-cliente/.project
  Pilgrimfy/it4-cliente/.settings/org.eclipse.core.resources.prefs
  Pilgrimfy/it4-cliente/.settings/org.eclipse.jdt.core.prefs
  Pilgrimfy/it4-cliente/.settings/org.eclipse.m2e.core.prefs
  Pilgrimfy/it4-cliente/pom.xml
  Pilgrimfy/it4-cliente/src/main/java/org/it4/cliente/presentacion/IU_ComentariosNegocio.java
  Pilgrimfy/it4-cliente/src/main/java/org/it4/cliente/presentacion/IU_ComentariosPeregrino.java
  Pilgrimfy/it4-cliente/src/test/java/org/it4/cliente/AppTest.java
  Pilgrimfy/it4-servidor/.classpath
  Pilgrimfy/it4-servidor/.gitignore
  Pilgrimfy/it4-servidor/.project
  Pilgrimfy/it4-servidor/.settings/org.eclipse.core.resources.prefs
  Pilgrimfy/it4-servidor/.settings/org.eclipse.jdt.core.prefs
  Pilgrimfy/it4-servidor/.settings/org.eclipse.m2e.core.prefs
  Pilgrimfy/it4-servidor/pom.xml
  Pilgrimfy/it4-servidor/src/main/java/org/it4/servidor/dominio/Comentario.java
  Pilgrimfy/it4-servidor/src/main/java/org/it4/servidor/dominio/GestorComentarios.java
  Pilgrimfy/it4-servidor/src/main/java/org/it4/servidor/persistencia/Agente.java
  Pilgrimfy/it4-servidor/src/test/java/org/it4/servidor/AppTest.java
  Pilgrimfy/pom.xml
Labels: Implementación

#41 Iteración2
  Pilgrimfy/it2-cliente/.classpath
  Pilgrimfy/it2-cliente/src/test/java/org/it2/cliente/presentacion/InterfazNegocioTest.java
  Pilgrimfy/it2-servidor/.classpath
  Pilgrimfy/it2-servidor/src/test/java/org/it2/servidor/dominio/GestorNegocioTest.java
  Pilgrimfy/it2-servidor/src/test/java/org/it2/servidor/dominio/NegocioTest.java
  Pilgrimfy/it2-servidor/src/test/java/org/it2/servidor/persistencia/AgenteTest.java
Labels: Pruebas

#42 Iteración4 Pruebas
  Pilgrimfy/it4-cliente/src/test/java/org/it4/cliente/presentacion/IU_ComentariosNegocioTest.java
  Pilgrimfy/it4-cliente/src/test/java/org/it4/cliente/presentacion/IU_ComentariosPeregrinoTest.java
  Pilgrimfy/it4-servidor/src/test/java/org/it4/servidor/dominio/ComentarioTest.java
  Pilgrimfy/it4-servidor/src/test/java/org/it4/servidor/dominio/GestorComentariosTest.java
  Pilgrimfy/it4-servidor/src/test/java/org/it4/servidor/persistencia/AgenteTest.java
Labels: Documentación, Pruebas

#43 Iteración3 Pruebas
  Pilgrimfy/it3-cliente/src/test/java/org/it3/cliente/AppTest.java
  Pilgrimfy/it3-cliente/src/test/java/org/it3/cliente/presentacion/IU_BuscarRecursoPeregrinoTest.java
  Pilgrimfy/it3-servidor/src/test/java/org/it3/servidor/AppTest.java
  Pilgrimfy/it3-servidor/src/test/java/org/it3/servidor/dominio/GestorRecursosTest.java
  Pilgrimfy/it3-servidor/src/test/java/org/it3/servidor/dominio/Google_MapsTest.java
  Pilgrimfy/it3-servidor/src/test/java/org/it3/servidor/dominio/RecursoTest.java
  Pilgrimfy/it3-servidor/src/test/java/org/it3/servidor/persistencia/AgenteTest.java
Labels: Pruebas

#45 Iteración5
  Pilgrimfy/it5-cliente/.classpath
  Pilgrimfy/it5-cliente/.gitignore
  Pilgrimfy/it5-cliente/.project
  Pilgrimfy/it5-cliente/.settings/org.eclipse.core.resources.prefs
  Pilgrimfy/it5-cliente/.settings/org.eclipse.jdt.core.prefs
  Pilgrimfy/it5-cliente/.settings/org.eclipse.m2e.core.prefs
  Pilgrimfy/it5-cliente/pom.xml
  Pilgrimfy/it5-cliente/src/main/java/org/it5/cliente/presentacion/InterfazLogin.java
  Pilgrimfy/it5-cliente/src/test/java/org/it5/cliente/AppTest.java
  Pilgrimfy/it5-servidor/.classpath
  Pilgrimfy/it5-servidor/.gitignore
  Pilgrimfy/it5-servidor/.project
  Pilgrimfy/it5-servidor/.settings/org.eclipse.core.resources.prefs
  Pilgrimfy/it5-servidor/.settings/org.eclipse.jdt.core.prefs
  Pilgrimfy/it5-servidor/.settings/org.eclipse.m2e.core.prefs
  Pilgrimfy/it5-servidor/pom.xml
  Pilgrimfy/it5-servidor/src/main/java/org/it5/servidor/dominio/GestorLogin.java
  Pilgrimfy/it5-servidor/src/main/java/org/it5/servidor/dominio/Persona.java
  Pilgrimfy/it5-servidor/src/main/java/org/it5/servidor/persistencia/Agente.java
  Pilgrimfy/it5-servidor/src/test/java/org/it5/servidor/AppTest.java
  Pilgrimfy/pom.xml
Labels: Implementación

#46 Iteración5
  Pilgrimfy/it5-cliente/src/test/java/org/it5/cliente/InterfazLoginTest.java
  Pilgrimfy/it5-servidor/src/main/java/org/it5/servidor/dominio/GestorLogin.java
  Pilgrimfy/it5-servidor/src/main/java/org/it5/servidor/dominio/Persona.java
  Pilgrimfy/it5-servidor/src/test/java/org/it5/servidor/dominio/GestorLoginTest.java
  Pilgrimfy/it5-servidor/src/test/java/org/it5/servidor/dominio/PersonaTest.java
  Pilgrimfy/it5-servidor/src/test/java/org/it5/servidor/persistencia/AgenteTest.java
Labels: Documentación, Pruebas

#48 Iteración6
  Pilgrimfy/it6-cliente/.classpath
  Pilgrimfy/it6-cliente/.gitignore
  Pilgrimfy/it6-cliente/.project
  Pilgrimfy/it6-cliente/.settings/org.eclipse.core.resources.prefs
  Pilgrimfy/it6-cliente/.settings/org.eclipse.jdt.core.prefs
  Pilgrimfy/it6-cliente/.settings/org.eclipse.m2e.core.prefs
  Pilgrimfy/it6-cliente/pom.xml
  Pilgrimfy/it6-cliente/src/main/java/org/it6/cliente/presentacion/InterfazEstadisticas.java
  Pilgrimfy/it6-cliente/src/test/java/org/it6/cliente/AppTest.java
  Pilgrimfy/it6-servidor/.classpath
  Pilgrimfy/it6-servidor/.gitignore
  Pilgrimfy/it6-servidor/.project
  Pilgrimfy/it6-servidor/.settings/org.eclipse.core.resources.prefs
  Pilgrimfy/it6-servidor/.settings/org.eclipse.jdt.core.prefs
  Pilgrimfy/it6-servidor/.settings/org.eclipse.m2e.core.prefs
  Pilgrimfy/it6-servidor/pom.xml
  Pilgrimfy/it6-servidor/src/main/java/org/it6/servidor/dominio/Estadistica.java
  Pilgrimfy/it6-servidor/src/main/java/org/it6/servidor/dominio/GestorEstadisticas.java
  Pilgrimfy/it6-servidor/src/main/java/org/it6/servidor/persistencia/Agente.java
  Pilgrimfy/it6-servidor/src/test/java/org/it6/servidor/AppTest.java
  Pilgrimfy/pom.xml
Labels: Implementación

#49 Iteración 6 Pruebas
  Pilgrimfy/it6-cliente/src/test/java/org/it6/cliente/AppTest.java
  Pilgrimfy/it6-cliente/src/test/java/org/it6/cliente/presentacion/InterfazEstadisticasTest.java
  Pilgrimfy/it6-servidor/src/test/java/org/it6/servidor/AppTest.java
  Pilgrimfy/it6-servidor/src/test/java/org/it6/servidor/dominio/EstadisticaTest.java
  Pilgrimfy/it6-servidor/src/test/java/org/it6/servidor/dominio/GestorEstadisticasTest.java
  Pilgrimfy/it6-servidor/src/test/java/org/it6/servidor/persistencia/AgenteTest.java
Labels: Pruebas

#51 Añadido fichero final de Visual Paradigm
  Pilgrimfy_Diagramas.vpp
Labels: Documentación
